### PR TITLE
Backup

### PR DESCRIPTION
**Pull request by nakamurataichi**
This change is [Reviewable](https://reviewable.io/reviews/comozilla/sphero-editor/26)

### CODE REVIEW

**Comment by dadaa** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[app/src/renderer/parser.js, line 29 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV6ZOsVxN11G_xhqBa:-KjV6ZOsVxN11G_xhqBb:bm94alb) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/parser.js#L29)):*
> ```JavaScript
>       roll(speed, degree, time) {
>         errors = errors.concat(checkArguments(arguments, ["number", "number", "number"]));
>         commands.push({ name: "roll", speed, degree, time });
> ```

引数が正しく無い場合でも、コマンドにプッシュしてしまって良いかしら？
checkArguments(arguments, ["number", "number", "number"]) が返す配列の長さが 1 以上である場合、コマンドを無視しないと壊れちゃいませんか？

---

*[app/src/renderer/parser.js, line 33 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV6gI4EcEtPpU1vPEf:-KjV6gI4EcEtPpU1vPEg:b-mbvgap) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/parser.js#L33)):*
> ```JavaScript
>       stop(time) {
>         errors = errors.concat(checkArguments(arguments, ["number"]));
>         commands.push({ name: "stop", time });
> ```

同様です。

---

*[app/src/renderer/sphero-manager.js, line 48 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV72ea39kB0zVcKFsr:-KjV72ebPICiFTbknlUt:bacvkjr) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/sphero-manager.js#L48)):*
> ```JavaScript
>         this.orb.roll(0, command.degree);
>         setTimeout(() => {
>           this.roll(command.speed, command.degree, command.time * 1000);
> ```

この 1000 もコンフィグに書き出しておきたいです。
つまり、秒を指定するかミリ秒を指定するかの設定がコンフィグで一発でできるようにしておくと良いかと思います。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by shundroid** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[app/src/renderer/parser.js, line 29 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV6ZOsVxN11G_xhqBa:-KjVcELkLawfY4rwsYpM:blm2cvs) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/parser.js#L29)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

引数が正しく無い場合でも、コマンドにプッシュしてしまって良いかしら？
checkArguments(arguments, ["number", "number", "number"]) が返す配列の長さが 1 以上である場合、コマンドを無視しないと壊れちゃいませんか？
</blockquote></details>

あ、たしかにそうですね。
となると、 errors.length === 0 のときのみ、 commands.push する感じがいいでしょうか

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by dadaa** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[app/src/renderer/parser.js, line 29 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV6ZOsVxN11G_xhqBa:-KjVhuDQq1gIMlWTYSvI:b-7rvexv) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/parser.js#L29)):*
<details><summary><i>Previously, shundroid wrote…</i></summary><blockquote>

あ、たしかにそうですね。
となると、 errors.length === 0 のときのみ、 commands.push する感じがいいでしょうか
</blockquote></details>

そうですね、それが良いかと思います

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by nakamurataichi** [comment]
*[app/src/renderer/parser.js, line 29 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV6ZOsVxN11G_xhqBa:-KjWcEl94SPqSg229nmd:b-g4q1ks) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/parser.js#L29)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

そうですね、それが良いかと思います
</blockquote></details>

わかりました。そうします

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by nakamurataichi** [comment]
*[app/src/renderer/sphero-manager.js, line 48 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV72ea39kB0zVcKFsr:-KjWiD8e_OmLSVwTb7-R:b-1cnvcz) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/sphero-manager.js#L48)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

この 1000 もコンフィグに書き出しておきたいです。
つまり、秒を指定するかミリ秒を指定するかの設定がコンフィグで一発でできるようにしておくと良いかと思います。
</blockquote></details>

ですね。そうします

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by dadaa** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[app/src/renderer/parser.js, line 33 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV6gI4EcEtPpU1vPEf:-KjYHF2gbyQjghjTWNKC:bo7epco) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/parser.js#L33)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

同様です。
</blockquote></details>

ここも errors.length === 0 のときのみ、 commands.push が良いかな。

---

*[app/src/renderer/sphero-manager.js, line 39 at r3](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjYHtOfdsOw-tfOJc9n:-KjYHtOgi14bLeM0je0G:b9339mp) ([raw file](https://github.com/comozilla/sphero-editor/blob/bbacada1b9d714cabac12b41b6f0d337193db6e2/app/src/renderer/sphero-manager.js#L39)):*
> ```JavaScript
>     let index = 0;
>     let currentDegree = 0;
>     const useMillisecond = config.Millisecond === true ? 1000 : 0;
> ```

config.isMillisecond のタイポかな？

あと、ミリセコンドが true のときは、おそらく useMillisecond は 1 で、秒のときは 1000 になると思います。
少なくとも 0 にしちゃうと、command.time * useMillisecond が 0 になっちゃいます。
もしかすると、config に isMillisecond : true/false ではなく、
setTimeoutAcceleration: 1000
とかして、掛ける数をそのまま書いても良いかもです。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by nakamurataichi** [comment]
*[app/src/renderer/sphero-manager.js, line 39 at r3](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjYHtOfdsOw-tfOJc9n:-Kjgxc0UGKNJ9h0hpRQp:bk3d23b) ([raw file](https://github.com/comozilla/sphero-editor/blob/bbacada1b9d714cabac12b41b6f0d337193db6e2/app/src/renderer/sphero-manager.js#L39)):*
>> config.isMillisecond のタイポかな？
そうです・・気をつけます。

>> あと、ミリセコンドが true のときは、おそらく useMillisecond は 1 で、秒のときは 1000 になると思います。
そうでした・・。

ミリ秒/秒 以外にすることってなさそうですけど、そうしたほうがいいでしょうか？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by dadaa** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[app/src/renderer/sphero-manager.js, line 39 at r3](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjYHtOfdsOw-tfOJc9n:-KjhiMLbVfuFmmCWSa7N:b-v9hhm1) ([raw file](https://github.com/comozilla/sphero-editor/blob/bbacada1b9d714cabac12b41b6f0d337193db6e2/app/src/renderer/sphero-manager.js#L39)):*
<details><summary><i>Previously, nakamurataichi (taichi) wrote…</i></summary><blockquote>

>> config.isMillisecond のタイポかな？
そうです・・気をつけます。

>> あと、ミリセコンドが true のときは、おそらく useMillisecond は 1 で、秒のときは 1000 になると思います。
そうでした・・。

ミリ秒/秒 以外にすることってなさそうですけど、そうしたほうがいいでしょうか？
</blockquote></details>

どっちでも良いかと思います。現在の方向で行くのだとしたら millisecond が基本なので、config.isSecondUnit みたいなコンフィグ名で true/false の設定をした方がわかりやすくなるかなと思います。
あと、いちおう、コンフィグの方にコメントを書いておくと良いですね。
useMillisecond の変数名は、commandTimeAcceleration とかがいいかなぁ、、

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by nakamurataichi** [comment]
*[app/src/renderer/sphero-manager.js, line 39 at r3](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjYHtOfdsOw-tfOJc9n:-KjmPkKJ2Itog5qkJOJx:b-gtkaot) ([raw file](https://github.com/comozilla/sphero-editor/blob/bbacada1b9d714cabac12b41b6f0d337193db6e2/app/src/renderer/sphero-manager.js#L39)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

どっちでも良いかと思います。現在の方向で行くのだとしたら millisecond が基本なので、config.isSecondUnit みたいなコンフィグ名で true/false の設定をした方がわかりやすくなるかなと思います。
あと、いちおう、コンフィグの方にコメントを書いておくと良いですね。
useMillisecond の変数名は、commandTimeAcceleration とかがいいかなぁ、、
</blockquote></details>

わかりました。直します

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by dadaa** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/renderer/gamepad-controller.js, line 12 at r4](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KlJGFmYR93xxXOk6GuE:-KlJGFmZesSu3n0EhUMt:bjh6cqr) ([raw file](https://github.com/comozilla/sphero-editor/blob/0522b51db5fb740201b959282c9b11e4d6c14bd9/app/src/renderer/gamepad-controller.js#L12)):*
> ```JavaScript
>   isButtonPressed(button) {
>     const isPressed = typeof button === "object" ? button.pressed : button === 1;
>     const index = this.isPressing.indexOf(button);
> ```

isPressing の名前が boolean ではなく配列なのでちょっと不思議な感じがします。
おそらく、ボタンのステータスをとっておきたいのかな？と、思いますけど、だとすると、たとえば、
pressingButtons とかでも良いかもです。

---

*[app/src/renderer/gamepad-controller.js, line 18 at r4](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KlJH5kZMjWaw4LWWIdH:-KlJH5kZMjWaw4LWWIdI:bviaoij) ([raw file](https://github.com/comozilla/sphero-editor/blob/0522b51db5fb740201b959282c9b11e4d6c14bd9/app/src/renderer/gamepad-controller.js#L18)):*
> ```JavaScript
>         return true;
>       }
>       return false;
> ```

ここも pressed の状態なので true を返す？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by nakamurataichi** [comment]
*[app/src/renderer/gamepad-controller.js, line 18 at r4](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KlJH5kZMjWaw4LWWIdH:-KlnAqA5G9iuuqZBbXRL:b-t22zge) ([raw file](https://github.com/comozilla/sphero-editor/blob/0522b51db5fb740201b959282c9b11e4d6c14bd9/app/src/renderer/gamepad-controller.js#L18)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

ここも pressed の状態なので true を返す？
</blockquote></details>

ここですが、続けて押したとき、それが押した判定になるのを防いでいます

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by dadaa** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/renderer/gamepad-controller.js, line 18 at r4](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KlJH5kZMjWaw4LWWIdH:-KmHa5pEg92V2Md5u2AD:bhgr7jo) ([raw file](https://github.com/comozilla/sphero-editor/blob/0522b51db5fb740201b959282c9b11e4d6c14bd9/app/src/renderer/gamepad-controller.js#L18)):*
<details><summary><i>Previously, nakamurataichi (taichi) wrote…</i></summary><blockquote>

ここですが、続けて押したとき、それが押した判定になるのを防いでいます
</blockquote></details>

なるほど

---

*[app/src/renderer/sphero-manager.js, line 19 at r5](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KmHal59ONQzjToCjEdY:-KmHal59ONQzjToCjEdZ:b5i9agt) ([raw file](https://github.com/comozilla/sphero-editor/blob/ef5d9bda696de4fe9172a24c23937341626477a8/app/src/renderer/sphero-manager.js#L19)):*
> ```JavaScript
>   }
>   run = commands => {
>     this.orb.color("purple");
> ```

定数的なものはコンフィグに書いてある方が良い気がします

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by dadaa** [comment]
Reviewed 3 of 9 files at r1, 6 of 10 files at r2, 1 of 3 files at r3, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by dadaa** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/renderer/gamepad-controller.js, line 12 at r4](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KlJGFmYR93xxXOk6GuE:-KmKXD9Mz7JJJF0LorXV:b32w0x) ([raw file](https://github.com/comozilla/sphero-editor/blob/0522b51db5fb740201b959282c9b11e4d6c14bd9/app/src/renderer/gamepad-controller.js#L12)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

isPressing の名前が boolean ではなく配列なのでちょっと不思議な感じがします。
おそらく、ボタンのステータスをとっておきたいのかな？と、思いますけど、だとすると、たとえば、
pressingButtons とかでも良いかもです。
</blockquote></details>

OK

---

*[app/src/renderer/gamepad-controller.js, line 18 at r4](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KlJH5kZMjWaw4LWWIdH:-KmKXFUpGn-ZpsUkCP49:b32w0x) ([raw file](https://github.com/comozilla/sphero-editor/blob/0522b51db5fb740201b959282c9b11e4d6c14bd9/app/src/renderer/gamepad-controller.js#L18)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

なるほど
</blockquote></details>

OK

---

*[app/src/renderer/parser.js, line 29 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV6ZOsVxN11G_xhqBa:-KmKXGuS2F8yQEyjBiVd:b32w0x) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/parser.js#L29)):*
<details><summary><i>Previously, nakamurataichi (taichi) wrote…</i></summary><blockquote>

わかりました。そうします
</blockquote></details>

OK

---

*[app/src/renderer/parser.js, line 33 at r2](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KjV6gI4EcEtPpU1vPEf:-KmKXHpnIdvmuxsQVtch:b32w0x) ([raw file](https://github.com/comozilla/sphero-editor/blob/3bac647327d102704ad9cfcb2e7c781ef2e3722f/app/src/renderer/parser.js#L33)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

ここも errors.length === 0 のときのみ、 commands.push が良いかな。
</blockquote></details>

OK

---

*[app/src/renderer/sphero-manager.js, line 19 at r5](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-KmHal59ONQzjToCjEdY:-KmKX9jmkPwX_VcX3ssg:b32w0x) ([raw file](https://github.com/comozilla/sphero-editor/blob/ef5d9bda696de4fe9172a24c23937341626477a8/app/src/renderer/sphero-manager.js#L19)):*
<details><summary><i>Previously, dadaa wrote…</i></summary><blockquote>

定数的なものはコンフィグに書いてある方が良い気がします
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26)*

**Comment by dadaa** [comment]
OK

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/comozilla/sphero-editor/26#-:-KmKXTCxG69bqaVYYFJk:b32w0x)*

**Pull request merged**
